### ISSUE TITLE
Allows other files to be downloaded too

### ISSUE THREAD

**Issue by rothbart837** [sdushantha/qr-filetransfer#1]
Can you update the code so _only_ the file passed via the command line parameter is shared?  For example, if you are in the directory where you cloned this repository and issue "./qr-filetransfer requirements.txt" and get a QR code that resolves to http://192.168.1.100:4415/requirements.txt and you modify that URL to replace "requirements.txt" with "screenshot.png", it'll serve up that screenshot too.  Worse yet, if you remove the filename from the URL, you end up with a browseable view of the directory you shared the file from:  http://192.168.1.100:4415 leads to:
Directory listing for /
.git/
qr-filetransfer.py
README.md
requirements.txt
screenshot.png

I realize this is supposed to be a quick and easy tool that's left running only for the duration of a quick file transfer, but it would be nice to _actually_ only be serving up one file when the purpose of this utility is to serve up one file.

**Comment by sdushantha** [comment]
I fixed it. Can you test it and see if it works on your machine?

**Comment by rothbart837** [comment]
If you get a URL via the QR code and delete the filename from it, it _still_ shows all the other files in that directory (meaning any file in the directory where the file you're serving up could possibly be served up over http with really simple URL manipulation.

Steps to reproduce:
- From a directory where your git is cloned, issue this command:
-  qr-filetransfer.py -f screenshot.png
- scan the QR code to get your URL
- You'll get a URL like http://192.168.1.1/screenshot.png
- Now, in your browser, remove "screenshot.png" from the URL
- You will see a listing of the entire directory.  
- Click on "requirements.txt" and it will display in the browser.  

That's the situation I was suggesting you avoid by copying the file you're serving into a randomly named unique directory so even though you're not solving the issue of being able to modify the URL, you're effectively making it useless because the only file you can browse is the one in that directory.

**Comment by sdushantha** [comment]
For me, when i remove the screenshot.png from the URL, I only see the file that is supposed to be shared. Ive linked a video here so you can see whats going on when i do it.

Video: https://streamable.com/iff1g

Also, PR #3 fixes the issue where the file gets deleted after the program runs

**Comment by CedArctic** [comment]
@rothbart837 You might have an older version, as @sdushantha said, the logic off the newer version is that a new temporary directory is created that only contains the file to be shared and only that directory is visible from the web server URL.
