### ISSUE TITLE
Add upload feature

### ISSUE THREAD

**Issue by sdushantha** [sdushantha/qr-filetransfer#20]
I found a script which is able to make simple http server and have an upload option. Do any one of you want to break the script apart and add this feature?

This would allow users to upload files from their phone to their computer with ease :)

https://gist.github.com/joonahn/5c21fde633bf61087fa3faea77e1f77f

@koddr
@hiancdtrsnm
@npes87184
@alexche8
@nchlssmsn
@MarcNo
@gr0t

**Comment by npes87184** [comment]
Hi,

I will take a look, Sunday.

Thanks.

**Comment by npes87184** [comment]
Hi, @sdushantha 

What behavior of uploading do you expect?

In this time, when we scan the QR code, the file download immediately.
There is no room to put the upload in this flow.

There are two simple proposition:
* Add upload mode. In this mode, after scanning QR code we will open a web contains upload button only.
* Desperate the behavior of scanning and downloading, the web contains file and upload button, user can (and should) choose what action to do (download or upload file).

Thanks.

**Comment by sdushantha** [comment]
I think there should be an upload mode/receive mode.
`$ qr-filetransfer -receive /path/to/receive/to`

The path will be where the file from the phone will be saved to. e.g `~/Downloads/`

So, your first proposition.
> Add upload mode. In this mode, after scanning QR code we will open a web contains upload button only.
