### ISSUE TITLE
Dependency install

### ISSUE THREAD

**Issue by Orthdron** [sdushantha/qr-filetransfer#30]
Environment: Linux bloop 5.0.12-arch2-1-ARCH #1 SMP PREEMPT Sat May 4 21:09:16 UTC 2019 x86_64 GNU/Linux

Installed this tool, upon running it, faced an error that says "iwgetid" not found.
I think this is used to fetch the wifi name.
is it possible to use any other tool to fetch the name of the network.

Thanks.

**Comment by sdushantha** [comment]
I am currently not able to be on a Linux machine at the moment.
Do you any other way to get the WiFi name?

I know that this is possible:
```bash
iw dev wlan0 scan
```
But I am not sure how to get the wireless interface of the user (e.g. `wlan0`). Because users might have a different wireless interface.

**Comment by Orthdron** [comment]
First run 
 ip link
and gather what interfaces are up 
and then proceed from there.

**Comment by sdushantha** [comment]
@Orthdron Would it be possible for you to make a pull request because I am not able to test this.

**Comment by npes87184** [comment]
Be sure to check each platform (Linux, Windows, MAC) can work, if you want to change the method to get wifi name.

I have met the same problem before, I simply installed [wireless_tools](https://www.archlinux.org/packages/core/x86_64/wireless_tools/) to overcome it.
