### ISSUE TITLE
Authenthication option

### ISSUE THREAD

**Issue by sdushantha** [sdushantha/qr-filetransfer#33]
Would be very cool if users could have a flag where they could pass a password and username so that when they scan the QR code and visit the url, they will be prompted with a username and password.

This would be very useful for people who would like extra security.

They could pass the credentials like this:
`username:password`

Here is an example on how the code would look like.
https://gist.github.com/fxsjy/5465353

---

@npes87184 Do you want to take this task? You are very good with the `socketserver` and `http.server` modules.

**Comment by npes87184** [comment]
I will take a look, when I have free time.
