### ISSUE TITLE
usage issue

### ISSUE THREAD

**Issue by riffAt2013** [sdushantha/qr-filetransfer#38]
I'm getting this message while transferring - "Make sure that your smartphone is connected to *None*"

Also, the scanner (default Xiaomi F1) can't scan the QR provided via the terminal. I've tried that in git-bash, cmder, and basic command line.

Tried the following
` qr-filetransfer.py /c/Users/RIFAT/Desktop/test.jpg`

**Comment by npes87184** [comment]
Hi,

Can you please try it again with `-d`?

For example
```
qr-filetransfer.py -d /c/Users/RIFAT/Desktop/test.jpg
```

This will print some msg for debugging usage.

Also, has your PC connected to wifi?

Thank you.

**Comment by riffAt2013** [comment]
It works after using the -d flag since It tells which address to enter, but still can't use the QR directly from cmder :(

```
python qr-filetransfer.py -d /c/Users/RIFAT/Desktop/test.jpg
Scan the following QR code to start downloading.
Make sure that your smartphone is connected to **None**
http://192.168.1.8:48931/test.jpg
```

My PC is not connected with the WiFI.

**Comment by npes87184** [comment]
> It works after using the -d flag since It tells which address to enter, but still can't use the QR directly from cmder :(

Ok, because of entering address directly works. It looks like your phone can connect to your pc through local ip. However, your phone cannot scan the code.

> 
> ```
> python qr-filetransfer.py -d /c/Users/RIFAT/Desktop/test.jpg
> Scan the following QR code to start downloading.
> Make sure that your smartphone is connected to **None**
> http://192.168.1.8:48931/test.jpg
> [[ QR HERE ]]
> ```
> 
> My PC is not connected with the WiFI.

It does not matter, if phone and PC in the same network environment.

IMO, the problem may be on the generated code or the scanner app.

Can you please try to use another app for scanning?

If it still not works, can you please provide the code here.

Thank you.

**Comment by riffAt2013** [comment]
I've tried with [QR Code reader](https://play.google.com/store/apps/details?id=com.apple.qrcode.readerl) and [QR & Barcode Reader](https://play.google.com/store/apps/details?id=com.teacapps.barcodescanner). only the latter scanned it perfectly.

Don't know why it didn't work with the former and the default Xiaomi F1 scanner.

Here's the qr generated for `python qr-filetransfer.py /c/Users/RIFAT/Desktop/test.jpg`

![qr](https://user-images.githubusercontent.com/34954502/70594159-d316ed80-1c09-11ea-9f35-1fd2cae89e56.PNG)

Would I close the issue since it worked for me anyway?

**Comment by sdushantha** [comment]
Since the problem has been solved, we can close it.
If you have any other questions, please feel free to ask :)
