### ISSUE TITLE
Not Downloading

### ISSUE THREAD

**Issue by puneethkanna** [sdushantha/qr-filetransfer#43]
When I try to send .txt and image and some other files, it is displaying instead of downloading.

**Comment by sdushantha** [comment]
I'm guessing what you mean is that the image just gets displayed in you phone's browser? That is the normal behaviour of your web browser and I doubt it has anything to do with `qr-filetransfer`. 
I dont think we can forcefully make you download a file using HTML as that would be a security issue. But if you try to transfer a file as a zip or a file which the browser is unable to display, it will prompt you to download it.

If you want to download the image, just press and hold on the video and you should be prompted to save the video.

**Comment by puneethkanna** [comment]
Yes, files which browser cannot display are prompted to download. But the txt, py and other files are also displayed.

**Comment by sdushantha** [comment]
> But the txt, py and other files are also displayed.

Yep. This is the expected behaviour of your web browser. If you want to transfer .py or .txt file to your phone, I would advice you to zip the file first and then send it to your phone.
